apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrupt-prod
spec:
  acme:
    server: https://acme-v02.api.letscrypt.org/directory
    email: 'myemail@gmail.com'
    privateKeySecretRef:
      name: letscrept-prod
    http01: {}
